
project_id = "vtoewarlzpjosljkhtwn"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.gong-webhook]
verify_jwt = false

[functions.scheduled-sync]
verify_jwt = false

[functions.test-velaris-token]
verify_jwt = false
