// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtoewarlzpjosljkhtwn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0b2V3YXJsenBqb3NsamtodHduIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0MjY0NzEsImV4cCI6MjA2NjAwMjQ3MX0.bI31hBa8jyy5zsrQ1ApMsP-fOEc4hKd2B2xlFOCZCDM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);